### ISSUE TITLE
ServerName should be set globally

### ISSUE THREAD

**Issue by LucaMiozzo** [evertramos/docker-wordpress-letsencrypt#16]
I've the error: AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using {IP.IP.IP.IP} Set the 'ServerName' directive globally to suppress this message

I run in the root folder the docker-compose with https://github.com/evertramos/docker-compose-letsencrypt-nginx-proxy-companion.git

and than in u sub folder the singular website with the docker-wordpress-letsencrypt where is the erro?

**Comment by ACChe** [comment]
@LucaMiozzo How to solved?

**Comment by LucaMiozzo** [comment]
> @LucaMiozzo How to solved?

I've reinstalled the docker service on the server and I've used a custom Dockerfile. 
But today I use other solutions for that and I don't have the code oth this fix.

sorry

**Comment by ACChe** [comment]
@LucaMiozzo All right, thanks.
