### ISSUE TITLE
Warning message: A number of scheduled tasks overdue.

### ISSUE THREAD

**Issue by xtjoeywx** [evertramos/docker-wordpress-letsencrypt#21]
Warning: WordPress has a number (4) of scheduled tasks which are overdue. Unless this is a development site, this probably means that the scheduler in your WordPress install is not working. Read this page for a guide to possible causes and how to fix it.

To recreate this problem, install the UpdraftPlus plugin and schedule automatic backups.
(I'm using Digital Ocean droplet and your docker-wordpress-letsencrypt.)

I'm guessing the issue is crons. I'm going to check to see if what this article says to do works: https://www.tring-web-design.co.uk/2016/02/wordpress-has-a-number-of-scheduled-tasks-which-are-overdue/
It says to add `define('ALTERNATE_WP_CRON', true);` to wp-config.php

I'll let it run for a day and then report back here to let you know if it fixed the problem.

**Comment by evertramos** [comment]
Hello @xtjoeywx!

I quiet did not understand the issue... I am running 18 WordPress sites behind our proxy and never had any issue with it.

What task did you have problem?

What was the error message?

It´s probably some plugin you are using not really this environment...

The wordpress cron tasks works smothly once it uses regular php services and the container itself comes from WordPress and has all php extension included. So, please, if you can, explain a little better what is this issue about.

Thanks!

**Comment by xtjoeywx** [comment]
After adding `define('ALTERNATE_WP_CRON', true);` to wp-config.php the problem is still there.

Please see the following screenshot to understand better about what I mean.
![screen shot 2018-07-31 at 8 38 08 pm](https://user-images.githubusercontent.com/35076109/43497968-04b654ec-9502-11e8-920f-14cc877e73ea.png)

**Comment by evertramos** [comment]
Hello @xtjoeywx, 

As I expected this is not an issue with the image neither the proxy itself... this plugin you are using it needs some requirements that it´s not standard to the wordpress image itself. You must open a ticket with the plugin to understand that this is, and might help if you check logs in your wp container to see what this plugin is trying to do... 

I also would suggestion you to inform the plugin that you are using the latest wordpress image on docker hub.

If you find the solution and could post it here, might help other to solve it.

Thanks!

**Comment by evertramos** [comment]
It seems to be only a warning... so your backup has probably being done corerctly... can you confirm that as well?

**Comment by xtjoeywx** [comment]
Thank you for your help. I’ll be sure to reach out to UpdraftPlus to talk to them about what guy said regarding the latest WordPress image.

Yes, backups complete if I manually click the backup button.
No, automatic backups are not working as they should.

Thanks for your help and also for making this these amazing tools.
