### ISSUE TITLE
Problems when creating a second WordPress

### ISSUE THREAD

**Issue by GoldraK** [evertramos/docker-wordpress-letsencrypt#24]
Hello,
I have created another WordPress on the same machine and it is well generated and I have both installed, but randomly the first wordpress loses the connection with the database of its docker.

If I deactivate the second wordpress, the first works perfectly.

Thanks for the help.

**Comment by evertramos** [comment]
Please update the **service name** on both environment and start it over.

**Comment by GoldraK** [comment]
Thanks work perfect now :)
