### ISSUE TITLE
Modify php.ini : max_input_vars

### ISSUE THREAD

**Issue by Tofdu31** [evertramos/docker-wordpress-letsencrypt#26]
Hi,

I need to increase the value for max_input_vars

I have to go to where for that?

**Comment by evertramos** [comment]
Hello @Tofdu31,

Add your php.ini options to:

https://github.com/evertramos/docker-wordpress-letsencrypt/blob/master/conf.d/php.ini

**Comment by Tofdu31** [comment]
Thank Evert,

```
file_uploads = On
memory_limit = 64M
upload_max_filesize = 64M
post_max_size = 64M
max_execution_time = 600
max_input_vars = 100000
```
I made the changes but I still have the error message
Here are the recommendations of my Jannah theme: 
https://jannah.helpscoutdocs.com/article/7-how-to-increase-the-php-max-input-vars

**Comment by evertramos** [comment]
yes Sir!

In fact the file name was `uploadsize.ini` I just updated to be more readable.

Thanks for the question.
