### ISSUE TITLE
Problem to download resources (themes, plugins...)

### ISSUE THREAD

**Issue by pierre-emmanuelJ** [evertramos/docker-wordpress-letsencrypt#27]
Hello  
when I want to download a theme or update plugin I get this window:

![image](https://user-images.githubusercontent.com/15922119/49525360-dfa58f00-f8ad-11e8-82f7-e72a17bb2c84.png)

**Comment by pierre-emmanuelJ** [comment]
Sorry I have solved this issue with that issue response:
https://github.com/evertramos/docker-wordpress-letsencrypt/issues/18

Thank you very much 👍 

Very nice repo!

**Comment by evertramos** [comment]
You are welcome!

Thanks for using it and your kind words.
