### ISSUE TITLE
Wordpress duplicator

### ISSUE THREAD

**Issue by Kubilai12** [evertramos/docker-wordpress-letsencrypt#28]
Hi

Can you explain me how i can move wordpress website with the duplicator plugin into the wordpress container build ?

i see i can build fresh install but it s hard to understand for migrate website

**Comment by evertramos** [comment]
Hello @Kubilai12!

It´s not that hard... you might will find a lot of useful information on youtube for that... this is not the real purpose of this repo, but you can send me an email I could professionally help you with that.

evert (dot) ramos (at) gmail
