### ISSUE TITLE
Website reset after container restart

### ISSUE THREAD

**Issue by kbitr** [evertramos/docker-wordpress-letsencrypt#30]
Maybe this is not related to the way the docker container are built, but every time I start an instance, import a backup from WP-Clone eg. and then restart the container, the website is set back to its state before the backup.

Any tips?

**Comment by evertramos** [comment]
Hello @kbitr,

This might be our of scope. of this repo... but you could check the database you set in the original site and the new one the database name, prefix etc... might be this part you forgot to set. It must be exactly the same as of the backup.

Cheers!

**Comment by cdseoo** [comment]
Hello @evertramos ，

I also encountered the same problem, how can I solve it?

**Comment by evertramos** [comment]
@cdseoo we will need some more information to help out... the database name and prefix are the same? starts from there.
