### ISSUE TITLE
admin area not working

### ISSUE THREAD

**Issue by Elmit2015** [evertramos/docker-wordpress-letsencrypt#38]
I have installed first the companion and then wordpress 

**Problems:**
1. The requested URL /wp-admin/install.php was not found on this server.
I solved by:
```
sudo chown www-data:www-data ./docker_data/site/wp-content
sudo chown www-data:www-data ./docker_data/site/wordpress-core/wp-content
```
Now I get the login window, however, after that I see:
The requested URL /wp-admin/ was not found on this server.

Changing the url to /wp-admin/index.php gets me one step further.

2. I tried to add a new user. Clicking on Add brings me to:
The requested URL /wp-admin/user-new.php was not found on this server.

The list goes on and on, ... 
I am sure it is just one small error, but I cannot see it.
How to solve that?

====
Update:
I found, that most of the 'missing pages' I get, if I just re-load the page.

====
Update:
I deleted the containers and data directories and started over. Same result.

Looking at the containers I have, I wonder if I interpreted the statement:
Starting your web containers
I issued the command:
```
docker run -d -e VIRTUAL_HOST=example.com \
-e LETSENCRYPT_HOST=example.com \
-e LETSENCRYPT_EMAIL=ronald@example.com \
--network=webproxy \
--name my_app \
httpd:alpine
```
I wonder what my_app is doing. Just tried to stop the container my_app and now my site is working.
When do I need to issue this command? and what is my_app ?

**Comment by evertramos** [comment]
Hello @Elmit2015 

Hope you are doing well.

Did you manage to make this work?
