### ISSUE TITLE
please upgrade wpcli with PHP 7.x

### ISSUE THREAD

**Issue by zachary** [evertramos/docker-wordpress-letsencrypt#43]
currently, only PHP 5.6.x works in wpcli

thanks

**Comment by evertramos** [comment]
@zachary we are using the wp-cli container latest version, so it will work with 7.x. not sure where you get this info, but please check your logs and see for yourself. Access containers and check again you will see the latest version of wordpress comes with php 7 and wp-cli works smothly as well.
