### ISSUE TITLE
Lets encrypt certificates are installed with the name of the proxy

### ISSUE THREAD

**Issue by yash-ks** [evertramos/docker-wordpress-letsencrypt#47]
There does not seem to be a place where this can be changed in the .env or the docker-compose files. This leads to Chrome and Safari complaining on visiting the domain that the certificate is not trustworthy and requires a scary override by user.

**Comment by evertramos** [comment]
This might be the issue you mentioned (here)[https://github.com/evertramos/docker-compose-letsencrypt-nginx-proxy-companion/issues/214]... the certificate verification is done by the proxy.. so your container here should use port 80 in this case. somehow you are trying to use the certificate in the container itself. And the certificates are located at /nginx-data/certs... please check.
